mess/accounting/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('mess.accounting.views',
    url(r'^listen_to_paypal$', 'listen_to_paypal', name='listen_to_paypal'),
    url(r'^paypal$', 'listen_to_paypal', name='paypal'),
    url(r'^transaction$', 'transaction', name='transaction'),
    url(r'^after_hours$', 'after_hours', name='after_hours'),
    url(r'^EBT$', 'EBT', name='EBT'),
    url(r'^close_out$', 'close_out', name='close_out'),
    url(r'^billing_old$', 'billing_old', name='billing_old'),
    url(r'^billing$', 'billing', name='billing'),
    url(r'^frozen$', 'frozen', name='frozen'),
    url(r'^cashsheet$', 'cashsheet', name='cashsheet'),
    url(r'^cashsheet_input$', 'cashsheet_input', name='cashsheet_input'),
    url(r'^hours_balance$', 'hours_balance', name='hours_balance'),
    url(r'^storeday$', 'storeday', name='storeday'),
    url(r'^ebt_bulk_orders$', 'EBT_bulk_orders', name='EBT-bulk-orders'),
    url(r'^ebt_bulk_orders/(?P<EBTBulkOrder_id>\d+)$', 
        'EBT_bulk_orders', name="EBT-bulk-orders-edit"),
    url(r'^diagnose_cashier_permission$','diagnose_cashier_permission',name='diagnose_cashier_permission'),
#   url(r'^reverse_trans$', 'reverse_trans', name='reverse_trans'),
    url(r'^equity_transfer/(\d+)$', 'equity_transfer', name='equity_transfer'),
)

mess/urls.py
from django.conf import settings 
from django.conf.urls.defaults import *
from django.contrib import admin
from django.contrib.auth import views as auth_views

admin.autodiscover()

urlpatterns = patterns('',
    (r'', include('mess.core.urls')),
    (r'^accounting/', include('mess.accounting.urls')),        
    (r'^membership/', include('mess.membership.urls')),        
    (r'^forum/', include('mess.forum.urls')),
    (r'^reporting/', include('mess.reporting.urls')),        
    (r'^scheduling/', include('mess.scheduling.urls')),        
    (r'^events/', include('mess.events.urls')),        

    # IS4C connector
    (r'^is4c/', include('mess.is4c.urls')),        

    #url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^passwordchange/$', auth_views.password_change, name='auth_password_change'),
    url(r'^passwordchange/done/$', auth_views.password_change_done, name='auth_password_change_done'),
    url(r'^passwordreset/$', auth_views.password_reset, name='auth_password_reset'),
    url(r'^passwordreset/done/$', auth_views.password_reset_done, name='auth_password_reset_done'),
    url(r'^passwordreset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, name='auth_password_reset_confirm'),
    url(r'^passwordreset/complete/$', auth_views.password_reset_complete, name='auth_password_reset_complete'),

    ('^admin/(.*)', admin.site.root),
)

urlpatterns += patterns('django.views.generic.simple', 
    (r'^styleguide$', 'direct_to_template', {'template': 'styleguide.html'}),
)

# We're going to use the Django server in development, so we'll serve
# the static content for now.
if settings.DEBUG:
    urlpatterns += patterns('', 
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', 
            {'document_root': settings.MEDIA_ROOT}),
    )

mess/accounting/models.py
from datetime import date

from django.db import models
from django.db.transaction import commit_on_success
from django.core import exceptions
from django.contrib.auth.models import User

from mess.settings import LOCATION
from mess.membership.models import Account, Member
from mess.membership import models as m_models

PURCHASE_CHOICES = (
    ('P','Purchase'),
    ('B','Bulk Purchase'),
    ('A','After-Hours Purchase'),
    ('U','Dues'),
    ('O','Member Equity'),
    ('G','Gift or Loan'),
    ('S','Misc'),   # Misc is used for transfers etc, positive or negative
#   ('T','Trade'),    what is Trade?
)

PAYMENT_CHOICES = (
    ('C','Credit Card'),
    ('D','Debit Card'),
    ('K','Check'),
    ('M','Money Order'),
    ('E','EBT'),
    ('W','Work Credit'),
    ('Y','Paypal'),
    ('A','Cash with Change'),
    ('B','Cash to Balance'),
    ('T','Gift Certificate'),
    ('O','Coupon'),
)

class HoursTransaction(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    account = models.ForeignKey(Account)
    hours_balance_change = models.DecimalField(max_digits=5, decimal_places=2,
        default=0, blank=True)
    note = models.CharField(max_length=256, blank=True)
    hours_balance = models.DecimalField(max_digits=5, decimal_places=2)
    entered_by = models.ForeignKey(User, blank=True, null=True)

    def save(self, *args, **kwargs):
        old_balance = self.account.hours_balance
        new_balance = old_balance + self.hours_balance_change
        self.account.hours_balance = self.hours_balance = new_balance
        self.account.save()
        super(HoursTransaction, self).save(*args, **kwargs)

class Transaction(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True) #never have to deal w/ this in a form.
    account = models.ForeignKey(Account)   # IS4C.account_id
    member = models.ForeignKey(Member, blank=True, null=True)
    purchase_type = models.CharField(max_length=1, choices=PURCHASE_CHOICES,
        blank=True, default='P')
    purchase_amount = models.DecimalField(max_digits=8, decimal_places=2, 
        default=0)   # this or payment_amount will hold the IS4C.total
    payment_type = models.CharField(max_length=1, choices=PAYMENT_CHOICES,
        blank=True)
    payment_amount = models.DecimalField(max_digits=8, decimal_places=2, 
        default=0)   # this or purchase_amount will hold the IS4C.total
    note = models.CharField(max_length=256, blank=True)   # IS4C.description
    account_balance = models.DecimalField(max_digits=8, decimal_places=2)
    entered_by = models.ForeignKey(User, blank=True, null=True)  # IS4C.emp_no

    # NEW FIELDS FOR IS4C
    register_no = models.IntegerField(blank=True, null=True)
    trans_id = models.IntegerField(blank=True, null=True)  #this is foreign pk for IS4C
    trans_no = models.IntegerField(blank=True, null=True)
    upc = models.CharField(max_length=13, blank=True)
    # TODO: trans_type : this needs a mapping, but let's also keep the original IS4C value
    trans_type = models.CharField(max_length=5, blank=True)
    trans_subtype = models.CharField(max_length=5, blank=True)
    department = models.IntegerField(blank=True, null=True)
    quantity = models.IntegerField(blank=True, null=True)
    # TODO: Kristina's example json has cost:2.73666666667, are we really limiting 
    # to decimal_places=2?
    cost = models.DecimalField(max_digits=8, decimal_places=2,
        default=0, blank=True)   
    taxable = models.NullBooleanField(blank=True, null=True)
    is4c_timestamp = models.DateTimeField(blank=True, null=True)
    is4c_cashier_id = models.IntegerField(blank=True, null=True)

    def __unicode__(self):
        return u'%s %s' % (self.account, 
                          self.timestamp.strftime('%Y-%m-%d %H:%M:%S'))

    def save(self, *args, **kwargs):
        if not self.member:
            raise Exception('all new transactions must have member')
        # purchase_amount and purchase_type must appear together
        if bool(self.purchase_amount) is not bool(self.purchase_type):
            self.purchase_amount = 0
            self.purchase_type = ''
        if bool(self.payment_amount) is not bool(self.payment_type):
            self.payment_amount = 0
            self.payment_type = ''

        if self.purchase_type == 'O':  
            print self.purchase_amount
            self.member.equity_held += self.purchase_amount

            # Per Dan's instructions, only update equity_due if the transaction is for a 
            # positive amount
            if self.purchase_amount > 0:
                self.member.equity_due -= self.purchase_amount

            if self.member.equity_due < 0:
                self.member.equity_due = 0
        balance = self.account.balance
        new_balance = balance + self.purchase_amount - self.payment_amount
        self.account.balance = self.account_balance = new_balance
        # put account and member save after transaction save so balance isn't
        # changed on transaction save error
        super(Transaction, self).save(*args, **kwargs)
        self.account.save()
        self.member.save()

    def save_for_equity_transfer(self, *args, **kwargs):
        # purchase_amount and purchase_type must appear together
        if bool(self.purchase_amount) is not bool(self.purchase_type):
            self.purchase_amount = 0
            self.purchase_type = ''
        if bool(self.payment_amount) is not bool(self.payment_type):
            self.payment_amount = 0
            self.payment_type = ''

        # equity should be recorded on account.deposit ONLY if member is unspecified.
        # if member is specified for equity transaction, then record on member.equity_held.
        if self.purchase_type == 'O':  
            if self.member is None:
                self.account.deposit += self.purchase_amount
            else:
                self.member.equity_held += self.purchase_amount
                self.member.equity_due -= self.purchase_amount
                if self.member.equity_due < 0:
                    self.member.equity_due = 0
                self.member.save()
        balance = self.account.balance
        new_balance = balance + self.purchase_amount - self.payment_amount
        self.account.balance = self.account_balance = new_balance
        # put account save after transaction save so balance isn't
        # changed on transaction save error
        super(Transaction, self).save(*args, **kwargs)
        self.account.save()

    def fixes_target(self):
        '''
        If this transaction is a correction, returns the target of the fix.
        Determined based on note starting with "@id "
        '''
        try:
            if self.note[0] == '@':
                target_id = self.note.split()[0][1:]
                target = Transaction.objects.get(id=target_id)
                if target.note and target.note[0] == '@':
                    return None  # disregard recursive fixers
                return target
        except:
            return [] # transaction was not a correction.

    def fixers(self):
        if self.note and self.note[0] == '@':
            return []  # disregard recursive fixers
        return Transaction.objects.filter(note__startswith='@%s ' % self.id)
        
    def fixed_payment_amount(self):
        payment = self.payment_amount
        for fixer in self.fixers():
            payment += fixer.payment_amount
        return payment

    def fixed_purchase_amount(self):
        purchase = self.purchase_amount
        for fixer in self.fixers():
            purchase += fixer.purchase_amount
        return purchase

    def reverse(self, entered_by, reason=''):
        ebtbo = self.ebtbulkorder_set.all()
        if ebtbo:
            for order in ebtbo:
                # do nothing.  trying to reduplicate the reversed EBT b.o.s
                # just creates more confusion.
                #order.duplicate_after_reversed()
                pass
        rev = Transaction(account=self.account,
                          member=self.member,
                          purchase_type=self.purchase_type,
                          purchase_amount= -self.fixed_purchase_amount(),
                          payment_type=self.payment_type,
                          payment_amount= -self.fixed_payment_amount(),
                          note='@%s reversed: %s' % (self.id, reason),
                          entered_by=entered_by)        
        rev.save()

    def note_plus_spaces(self):
        return self.note.replace('+',' + ')

    class Meta:
        ordering = ['timestamp']
        

class EBTBulkOrderManager(models.Manager):
    def unpaid(self):
        return self.filter(paid_by_transaction__isnull=True, amount__gt=0)
    def paid(self):
        return self.exclude(paid_by_transaction__isnull=True, amount__gt=0)

class EBTBulkOrder(models.Model):
    order_date = models.DateTimeField(auto_now_add=True)
    account = models.ForeignKey(Account)
    amount = models.DecimalField(max_digits=8, decimal_places=2,
        default=0)
    paid_by_transaction = models.ForeignKey(Transaction, null=True)
    note = models.CharField(max_length=256, blank=True)

    objects = EBTBulkOrderManager()

    def __unicode__(self):
        return u'%s EBT bulk ordered %s on %s' % (self.account, 
                self.amount, self.order_date)

    def duplicate_after_reversed(self):
        """ this is called when the order was already paid, but then
        the transaction was reversed.  we create a duplicate of the original
        EBT bulk order. """
        duplicate = EBTBulkOrder(order_date=self.order_date,
                account=self.account,
                amount=self.amount,
                note='(reversed) '+self.note)
        duplicate.save()

    def save(self, *args, **kwargs):
        if self.id:
            oldself = EBTBulkOrder.objects.get(id=self.id)
            if oldself.paid_by_transaction:

mess/templates/accounting/snippets/acct_flags.html
{% if account.frozen_flags %}
  <div class="frozen">
    {{ account.frozen_flags|join:" ... " }}
  </div>
{% endif %}{% if account.ebtbulkorder_set.unpaid %}
  <div class="notice">
    EBT Bulk Order
  </div>
{% endif %}{% if show_acct_link %}
  <a href="{{ account.get_absolute_url }}">view account</a>
{% endif %}

mess/templates/accounting/snippets/acctinfo.html
<h4>{% if request.user.is_staff %}<a href="{{ account.get_absolute_url }}">view</a>{% endif %}{{ account.name }}</h4>
<ul class="quick-info">
  <li>{{ account.verbose_balance }}</li>
  <li>Hours balance: {{ account.hours_balance }}</li>
<!-- secret? <li>Max allowed to owe: {{ account.max_allowed_to_owe|floatformat:2 }}</li> -->
<!-- may be wrong <li>Can Shop: {{ account.can_shop|yesno }}</li> -->
</ul>
{% if account.ebt_only %}<h4>EBT Only</h4>{% endif %}
{% if account.obligations %}<h4>{{ account.obligations }}</h4>{% endif %}
{% if account.must_work %}<h4 class="warning">Owes Hours</h4>{% endif %}
{% if account.must_pay %}<h4 class="warning">Owes Balance {{ account.must_pay }}</h4>{% endif %}
{% if not account.can_shop %}<h4 class="warning">CAN NOT SHOP</h4>{% endif %}
{% if not account.active_member_count %}<h4 class="warning">ACCOUNT CLOSED</h4>{% endif %}

mess/templates/accounting/snippets/confirm_other_member.html
Which member from<br />
<span style='color: red;'>{{ account_name }}<br /></span>
is authorizing this transaction by<br />
<span style='color: red;'>{{ other_member_name }}</span>?"

<ul>
{% for id, name in account_members.items %}
<li class=confirm_member id={{ id }}
        onclick="set_other_member(this,'{{ other_member_id }}','{{ other_member_name }}');">{{ name }}</li>
{% endfor %}
</ul>
<div class=confirm_member id=cancel onclick="set_member(this);">No one, please cancel!</div>

mess/templates/accounting/snippets/hours_balance_changes.html
<table class="data">
  <tr>
    <th>Time</th>
    <th>Account</th>
    <th>Hours<br>Balance<br>Change</th>
    <th>Hours<br>Balance</th>
    <th>Entered<br>By</th>
  </tr>
  {% if hours_transactions %}
    {% for transaction in hours_transactions|dictsortreversed:"id" %}
      <tr class="{% cycle 'odd' 'even' %}">
        <td>{{ transaction.timestamp|date:"n/j g:i A Y" }}</td>
        <td><a href="{{ transaction.account.get_absolute_url }}">{{ transaction.account }}</a></td>
        <td>{{ transaction.hours_balance_change }}</td>
        <td>{{ transaction.hours_balance }}</td>
        <td>{{ transaction.entered_by.username }}</td>
      </tr>
    {% endfor %}
  {% endif %}
</table>

mess/templates/accounting/snippets/list.html
<div id=list_cancel >Cancel</div>

{% if accounts %}
    <div id=account_list >
    {% for id, name in accounts.items %}
        <div class=account_choice id={{ id }} >{{ name }}</div>
    {% endfor %}
    </div>
{% endif %}

{% if account_members %}
    <div id=account_members >
    {% for id, name in account_members.items %}
        <div class=member_choice id={{ id }} >{{ name }}</div>
    {% endfor %}
    </div>
{% endif %}
</div>
{% if members %}
    <div class=other_member_choice >------- Other members ---------</div>
    <div id=other_members >
    {% for id, name in members.items %}
        <div class=other_choice id={{ id }} >{{ name }}</div>
    {% endfor %}
    </div>
{% endif %}

mess/templates/accounting/snippets/local_nav.html
{% block local_nav %}
<ul class="local-nav">
  <li><a {% ifequal local_nav "cashier" %} class="active"{% endifequal %} href="{% url close_out %}">Cashier</a></li>
  <li><a {% ifequal local_nav "close_out" %} class="active"{% endifequal %} class="last-item"><a href="{% url close_out %}">Close Out</a></li>
</ul>
{% endblock %}

mess/templates/accounting/snippets/members.html
<option value="" selected="selected">---------</option>
{% for member in account.members.all %}
  <option value="{{ member.id }}">{{ member }}{% if not member.is_active %}{% if member.date_departed %} (departed){% else %} (missing?){% endif %}{% endif %}{% if member.is_on_loa %} (on leave until {{ member.current_loa.end|date:"n/j/Y" }}){% endif %}</option>
{% endfor %}

mess/templates/accounting/snippets/page_menu.html
{% block page_menu %}
{% load core_tags %}
  <ul id="local-nav">
    {# Staff assistants should only be able to see the transactions tab, which is the default tab, so we don't need the page menu for staff assistants #}
    {% if user.is_staff or not is_staff_assistant %}
    <li><a href="{% url hours_balance %}"{% if location.path|match:'/accounting/hours_balance' %} class="active"{% endif %}>Hours Balance</a></li>
    <li><a href="{% url transaction %}"{% if location.path|match:'/accounting/transaction' %} class="active"{% endif %}>Transaction</a></li>
    {# <li><a href="{% url after_hours %}"{% if location.path|match:'/accounting/after_hours' %} class="active"{% endif %}>After-hours</a></li> #}
    {# <li><a href="{% url EBT %}"{% if location.path|match:'/accounting/EBT' %} class="active"{% endif %}>EBT</a></li> #}
    <li><a href="{% url EBT-bulk-orders %}"{% if location.path|match:'/accounting/ebt_bulk_orders' %} class="active"{% endif %}>Create EBT Bulk Orders</a></li>
    {# <li><a href="{% url cashsheet_input %}"{% if location.path|match:'/accounting/cashsheet_input' %} class="active"{% endif %}>Cashsheet Input</a></li> #}
    <li class="last-item"><a href="{% url close_out %}"{% if location.path|match:'/accounting/close_out' %} class="active"{% endif %}>Close Out</a></li>
    {% endif %}
  </ul>
{% endblock %}

mess/templates/accounting/snippets/transactions.html
{% load messmoney %}

<form action="{% url cashsheet_input %}" method="post" id="reverse_form">
  {% csrf_token %}
  <input type="hidden" name="reverse_id" id="id_reverse_id">
  <input type="hidden" name="reverse_reason" id="id_reverse_reason">
  <input type="hidden" name="action" value="Reverse">
</form>

<table class="data" >
  <tr>
    <th>ID</th>
    <th>Time</th>
    <th>Account</th>
    <th>Member</th>
    <th>Note</th>
    <th>Purchase Type</th>
    <th>Purchase Amount</th>
    <th>Payment Type</th>
    <th>Payment Amount</th>
    <th>Account<br />Balance</th>
    <th>Entered<br />By</th>
  </tr>
  {% if transactions %}
    {% for transaction in transactions|dictsortreversed:"id" %}
  <tr class="{% cycle 'odd' 'even' %}" >
    <td>{{ transaction.id }}</td>
    <td class="nowrap">{{ transaction.timestamp|date:"n/j/Y g:iA" }}</td>
    <td><a href="{{ transaction.account.get_absolute_url }}">{{ transaction.account }}</a></td>
    <td>{% if transaction.member %}<a href="{{ transaction.member.get_absolute_url }}">{{ transaction.member }}</a>{% endif %}</td>
    <td>{{ transaction.note_plus_spaces }}</td>
    <td>{{ transaction.get_purchase_type_display }}</td>
    <td>{% if transaction.purchase_amount %}{{ transaction.purchase_amount|messmoney }}{% endif %}</td>
    <td>{{ transaction.get_payment_type_display }}</td>
    <td>{% if transaction.payment_amount %}{{ transaction.payment_amount|messmoney:"payment" }}{% endif %}</td>
    <td>{{ transaction.account_balance|messmoney }}</td>
    <td>{{ transaction.entered_by.username }}{% if can_reverse and not transaction.fixes_target and not transaction.fixers %} <input type="button" value="X" onclick="reverse_trans({{ transaction.id }}, '{{ transaction.account|addslashes }}');">{% endif %}</td>
  </tr>
    {% endfor %}
  {% endif %}
</table>