mess/membership/urls.py
from django.conf.urls.defaults import *
from mess.membership import models
from mess.autocomplete.views import autocomplete
from django.db.models import Q
from django.contrib.auth import views as auth_views

autocomplete.register('account', models.Account.objects.all(), ('name__istartswith',), limit=10, label='name')

# create hook to branch autocomplete filter: '* = include inactive'
# (this doesn't belong here in urls.py, but where should it live?)
def member_spiffy_filter(query):
    if '*' in query:
        plain_query = query.strip('* ')
        return (Q(user__first_name__istartswith=plain_query) |
                Q(user__last_name__istartswith=plain_query) |
                Q(accounts__name__istartswith=plain_query))
    else:
        return (Q(id__in=models.Member.objects.active()) &
                   (Q(user__first_name__istartswith=query) |
                    Q(user__last_name__istartswith=query) |
                    Q(accounts__name__istartswith=query)))

autocomplete.register('member_spiffy', models.Member.objects.all(), member_spiffy_filter, limit=10, label=lambda m: m.autocomplete_label() )

def account_spiffy_filter(query):
    if '*' in query:
        plain_query = query.strip('* ')
        return Q(name__istartswith=plain_query)
    else:
        return ((Q(id__in=models.Account.objects.active()) |
                Q(name='One-Time Shopper')) &
                Q(name__istartswith=query))

autocomplete.register('account_spiffy', models.Account.objects.all(), account_spiffy_filter, limit=10, label=lambda a: a.autocomplete_label() )

urlpatterns = patterns('mess.membership.views',
    url(r'^accounts$', 'accounts', name='accounts'),
    url(r'^accounts/add$', 'account_form', name='account-add'),
    url(r'^accounts/(\d+)$', 'account', name='account'),
    url(r'^accounts/(\d+)/edit$', 'account_form', name='account-edit'),
    url(r'^accounts/(\d+)/depart$', 'depart_account', name='depart-account'),
    url(r'^accounts/(\d+)/loa$', 'loa_account', name='loa-account'),
    url(r'^accounts/(\d+)/templimit$', 'templimit', name='templimit'),
    url(r'^members$', 'members', name='members'),
    url(r'^members/add$', 'member_form', name='member-add'),
    url(r'^members/(\w+)$', 'member', name='member'),
    url(r'^members/(\w+)/edit$', 'member_form', name='member-edit'),
    url(r'^formset-form/(\w+)$', 'formset_form', name='membership-formset-form'),

    url(r'^(?P<username>\w+)/add_(?P<medium>\w+)/$', 'contact_form', name='membership-add-contact'),

    url(r'^(?P<username>\w+)/edit_(?P<medium>\w+)/(?P<id>\d+)$', 'contact_form', name='membership-edit-contact'),
    url(r'^(?P<username>\w+)/edit_address/(?P<id>\d+)$', 'contact_form', kwargs={'medium': 'address'}, name='membership-edit-address'),
    url(r'^(?P<username>\w+)/edit_email/(?P<id>\d+)$', 'contact_form', kwargs={'medium': 'email'}, name='membership-edit-email'),
    url(r'^(?P<username>\w+)/edit_phone/(?P<id>\d+)$', 'contact_form', kwargs={'medium': 'phone'}, name='membership-edit-phone'),

    url(r'^(?P<username>\w+)/remove_(?P<medium>\w+)/(?P<id>\d+)$', 'remove_contact', name='membership-remove-contact'),
    url(r'^(?P<username>\w+)/remove_address/(?P<id>\d+)$', 'remove_contact', kwargs={'medium': 'address'}, name='membership-remove-address'),
    url(r'^(?P<username>\w+)/remove_email/(?P<id>\d+)$', 'remove_contact', kwargs={'medium': 'email'}, name='membership-remove-email'),
    url(r'^(?P<username>\w+)/remove_phone/(?P<id>\d+)$', 'remove_contact', kwargs={'medium': 'phone'}, name='membership-remove-phone'),

    url(r'^autocomplete/(\w+)/$', autocomplete, name='membership-autocomplete'),
    url(r'^accountmemberflags/$', 'accountmemberflags', name='accountmemberflags'),

    url(r'^(?P<username>\w+)/adminresetpassword/$', 'admin_reset_password', name='admin_reset_password'),
    url(r'^signup/member/$', 'member_signup', name='member-signup'),
    url(r'^signup/member/(\d+)/edit/$', 'member_signup_edit', name='member-signup-edit'),
    url(r'^signup/member/review/$', 'member_signup_review', name='member-signup-review'),
    url(r'^signup/orientation/$', 'orientation_signup', name='orientation-signup'),

    #url(r'^rawlist/$', 'raw_list', name='membership-raw-list')
    #url('^junkx/(\w+)/$', junk, name='junkx'),
)

mess/urls.py
from django.conf import settings 
from django.conf.urls.defaults import *
from django.contrib import admin
from django.contrib.auth import views as auth_views

admin.autodiscover()

urlpatterns = patterns('',
    (r'', include('mess.core.urls')),
    (r'^accounting/', include('mess.accounting.urls')),        
    (r'^membership/', include('mess.membership.urls')),        
    (r'^forum/', include('mess.forum.urls')),
    (r'^reporting/', include('mess.reporting.urls')),        
    (r'^scheduling/', include('mess.scheduling.urls')),        
    (r'^events/', include('mess.events.urls')),        

    # IS4C connector
    (r'^is4c/', include('mess.is4c.urls')),        

    #url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^passwordchange/$', auth_views.password_change, name='auth_password_change'),
    url(r'^passwordchange/done/$', auth_views.password_change_done, name='auth_password_change_done'),
    url(r'^passwordreset/$', auth_views.password_reset, name='auth_password_reset'),
    url(r'^passwordreset/done/$', auth_views.password_reset_done, name='auth_password_reset_done'),
    url(r'^passwordreset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, name='auth_password_reset_confirm'),
    url(r'^passwordreset/complete/$', auth_views.password_reset_complete, name='auth_password_reset_complete'),

    ('^admin/(.*)', admin.site.root),
)

urlpatterns += patterns('django.views.generic.simple', 
    (r'^styleguide$', 'direct_to_template', {'template': 'styleguide.html'}),
)

# We're going to use the Django server in development, so we'll serve
# the static content for now.
if settings.DEBUG:
    urlpatterns += patterns('', 
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', 
            {'document_root': settings.MEDIA_ROOT}),
    )

mess/membership/forms.py
from django import forms
from django.contrib.auth.models import User, Group
from django.forms import formsets
from django.forms.models import inlineformset_factory, modelformset_factory
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError

from mess.membership import models
from mess.events import models as e_models
from mess.autocomplete import AutoCompleteWidget
import datetime

AddressFormSet = inlineformset_factory(models.Member, models.Address, 
        extra=0) #, min_num=1)
PhoneFormSet = inlineformset_factory(models.Member, models.Phone, 
        extra=0) #, min_num=1)
LeaveOfAbsenceFormSet = inlineformset_factory(models.Member, models.LeaveOfAbsence, 
        extra=0) #, min_num=1)
RelatedAccountFormSet = inlineformset_factory(models.Member, 
        models.AccountMember, exclude=('primary_account',), extra=0)
RelatedMemberFormSet = inlineformset_factory(models.Account, 
        models.AccountMember, exclude=('primary_account',), extra=0)

# forms below needed for dynamic formsets
class AddressForm(forms.ModelForm):
    class Meta:
        model = models.Address
        exclude = ('member',)

class PhoneForm(forms.ModelForm):
    class Meta:
        model = models.Phone
        exclude = ('member',)

class LeaveOfAbsenceForm(forms.ModelForm):
    class Meta:
        model = models.LeaveOfAbsence
        exclude = ('member',)

class RelatedAccountForm(forms.ModelForm):
    class Meta:
        model = models.AccountMember
        exclude = ('member', 'primary_account')

class RelatedMemberForm(forms.ModelForm):
    class Meta:
        model = models.AccountMember
        exclude = ('account', 'primary_account')

class MemberForm(forms.ModelForm):
    class Meta:
        model = models.Member
        exclude = ('status', 'user', 'equity_held')

class UserEmailForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'groups')
    # username pulled straight from django/contrib/auth/forms.py
    username = forms.RegexField(label=_("Username"), max_length=30, 
            regex=r'^\w+$', help_text = _("Required. 30 characters or fewer. Alphanumeric characters only (letters, digits and underscores)."),
            error_message = _("This value must contain only letters, numbers and underscores."))
    # groups pulled from django/contrib/auth/models.py and augmented
    groups = forms.ModelMultipleChoiceField(Group.objects.all(),
        help_text=_('Hold down "Control", or "Command" on a Mac, to select more than one.'),
        required=False)

class AccountForm(forms.ModelForm):
    class Meta:
        model = models.Account
        exclude = ('balance', 'deposit', 'members', 'can_shop')

MEMBER_SORT_CHOICES = (
    ('alpha', 'Alphabetical'),
    ('newjoin', 'Date joined (newest first)'),
    ('oldjoin', 'Date joined (oldest first)'),
)

ACCOUNT_SORT_CHOICES = (
    ('alpha', 'Alphabetical'),
    ('recent', 'Most recently added'),
    ('hours', 'Hours balance (high to low)'),
    ('balance', 'Account balance (high to low)'),
)

class MemberListFilterForm(forms.Form):
    search = forms.CharField(required=False)
    sort_by = forms.ChoiceField(choices=MEMBER_SORT_CHOICES)
    active = forms.BooleanField(initial=True, required=False)
    leave_of_absence = forms.BooleanField(initial=False, required=False)
    missing = forms.BooleanField(initial=False, required=False)
    missing_delinquent = forms.BooleanField(initial=False, required=False)
    departed = forms.BooleanField(initial=False, required=False)

class DateForm(forms.Form):
    day = forms.DateField(initial = datetime.date.today)

class PickMemberForm(forms.Form):
    member = forms.ModelChoiceField(models.Member.objects.all(),
        widget=AutoCompleteWidget('member_spiffy',
            view_name='membership-autocomplete', canroundtrip=True))

class TemporaryBalanceLimitForm(forms.ModelForm):
    class Meta:
        model = models.TemporaryBalanceLimit
        fields = ['limit','until']

class LoaForm(forms.Form):
    ENDDEF = 365  # days from today for endtime default
    start = forms.DateField(initial=datetime.date.today)
    default_end = datetime.date.today() + datetime.timedelta(ENDDEF)
    end = forms.DateField(initial=default_end)
    c_tuple = (('short', 'free each shift for one-time fill'),
               ('long', 'remove members from shifts entirely'))
    shifts_during_LOA = forms.ChoiceField(choices=c_tuple,
                                          widget=forms.RadioSelect, 
                                          initial='long')

class AccountListFilterForm(forms.Form):
    search = forms.CharField(required=False)
    sort_by = forms.ChoiceField(choices=ACCOUNT_SORT_CHOICES)
    active = forms.BooleanField(initial=True, required=False)
    inactive = forms.BooleanField(initial=False, required=False)
#   can_shop = forms.BooleanField(initial=True, required=False)
#   ebt_only = forms.BooleanField(initial=True, required=False)

def mess_get_orientation_choices(upcoming_orientations_only):
    """ 
    Helper function that returns all upcoming (and active)
    orientations as well as our two special orientations:
    Returning member, and None of these dates work for me 
    """
    if not upcoming_orientations_only:
        returning_member_orientation = e_models.Orientation.objects.get(id=1)

    orientations = e_models.Orientation.objects.filter(active=True).filter(start__gte=datetime.datetime.now()).order_by('start')

    if not upcoming_orientations_only:
        no_dates_orientation = e_models.Orientation.objects.get(id=2)
    
    orientation_choices = [('','')]

    if not upcoming_orientations_only:
        orientation_choices.append((returning_member_orientation.id, returning_member_orientation.name))

    for orientation in orientations:
        orientation_choices.append((orientation.id, orientation.name))

    if not upcoming_orientations_only:
        orientation_choices.append((no_dates_orientation.id, no_dates_orientation.name))

    return orientation_choices


class MemberSignUpForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super(MemberSignUpForm, self).__init__(*args, **kwargs)
        self.fields["orientation"].choices = mess_get_orientation_choices(False)

#    def clean_email(self):
#        data = self.cleaned_data["email"]
#
#        if User.objects.filter(email=data).count() > 0:
#            raise ValidationError(u'The email address %s is already in use by an existing member. If you are a returning member, please write to membership@mariposa.coop to inquire about restoring your membership at Mariposa.')
#
#        return data

    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=False)
    phone = forms.CharField(required=True)
    street_address = forms.CharField(required=True)
    city = forms.CharField(required=True, initial="Philadelphia")
    state = forms.CharField(required=True, initial="PA")
    postal_code = forms.CharField(required=True, initial="19143")
    referral_source = forms.ChoiceField(required=False, choices=models.REFERRAL_SOURCES)
    referring_member = forms.CharField(required=False)
    terms = forms.BooleanField(required=True, initial=False)
    orientation = forms.ChoiceField(required=True)
    equity_paid = forms.ChoiceField(required=True, choices=models.EQUITY_PAID_OPTIONS)

class MemberSignUpEditForm(forms.ModelForm):
    class Meta:
        model = models.MemberSignUp

class MemberSignUpReviewForm(forms.Form):

#    def __init__(self, *args, **kwargs):
#        super(MemberSignUpReviewForm, self).__init__(*args, **kwargs)
#        
#        members = models.Member.objects.filter(date_departed__isnull=True)
#        member_choices = [('','')]
#
#        for member in members:
#            member_choices.append((member.id, str(member)))
#        
#        self.fields["referring_member"].choices = member_choices

    def clean_user_name(self):
     
        value = self.cleaned_data['user_name']

        if (value.strip()==''):
            raise ValidationError(u'The user name must not be blank')
    
        if (User.objects.filter(username=value.strip()).count() > 0):
            raise ValidationError(u'The user name %s already exists' % value)

        return value

    def set_referring_member_choices(self, choices):
        self.fields["referring_member"].choices = choices

    record_id = forms.IntegerField(widget=forms.HiddenInput, required=False)
    selected = forms.BooleanField(initial=False, required=False)
    name = forms.CharField(widget=forms.HiddenInput, required=False)
    user_name = forms.CharField(max_length=30, required=False)
    email = forms.CharField(widget=forms.HiddenInput, required=False)
    phone = forms.CharField(widget=forms.HiddenInput, required=False)
    address1 = forms.CharField(widget=forms.HiddenInput, required=False)
    city = forms.CharField(widget=forms.HiddenInput, required=False)
    state = forms.CharField(widget=forms.HiddenInput, required=False)
    postal_code = forms.CharField(widget=forms.HiddenInput, required=False)
    referral_source = forms.CharField(widget=forms.HiddenInput, required=False)
    referring_member = forms.ChoiceField(required=False)
    orientation = forms.CharField(widget=forms.HiddenInput, required=False)
    equity_paid = forms.CharField(widget=forms.HiddenInput, required=False)
    payment_verified = forms.BooleanField(initial=False, required=False)

class OrientationSignUpForm(forms.Form):
    
    def __init__(self, *args, **kwargs):
        super(OrientationSignUpForm, self).__init__(*args, **kwargs)
        self.fields["orientation"].choices = mess_get_orientation_choices(True)

    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

mess/templates/membership/account.html
{% extends "base.html" %}
{% load messmoney %}
{% load messhours %}

{% block content %}
  <div id="left-column">
    {% include "membership/snippets/page_menu.html" %}
    <div id="primary-content-wrapper">
      <h2 class="accountname">
        {% if user.is_staff %}
          <span class="accountactionlinks">
            <a href="{% url account-edit account.id %}">edit</a>
            <a href="{% url loa-account account.id %}">loa</a>
            <a href="{% url depart-account account.id %}">depart</a>
          </span>
        {% endif %}
        {{ account }}
      </h2>
      {% include "accounting/snippets/acct_flags.html" %}

        <div class="accountinfo">
      <div class="accountmemberside">
        <ul class="quick-info">
          <li><b>{% if account.owes_money %}Money owed{% else %}Credit{% endif %}:</b> 
            {{ account.balance|messmoney }}</li>
          <li><b>Discount:</b> {{ account.discount }}%</li>
          <li>
            <b>Balance limit:</b> {% if account.temporarybalancelimit_set.current %}{{ account.temporarybalancelimit_set.current|first }}{% else %}{{ account.max_allowed_to_owe }}{% endif %}
            {% if request.user.is_staff %}
              <br /><a href="{{ account.get_templimit_url }}">change balance limit</a>
            {% endif %}
          </li>
        </ul>
        </div>

      <div class="accountmemberside">
        <ul class="quick-info">
          <li>
          {% if account.unexcused_hours_owed %}<b>Unexcused hours owed</b>: {{ account.hours_balance|messhours:"unexcused" }}{% endif %}
          </li>
          <li><b>{% if account.excused_hours_owed %}Excused hours owed{% else %}Hours banked{% endif %}:</b> 
            {{ account.hours_balance|messhours }} 
            {% if request.user.is_staff %}<a href="{{ account.get_hours_balance_history_url }}">history</a>{% endif %}
          </li>

          <li><b>Shared address:</b> {% if account.shared_address %}Yes{% else %}No{% endif %}</li>
          {% if account.deposit %}<li><b>Equity still linked to account:</b> {{ account.deposit|messmoney }}</li>{% endif %}
        </ul>
        </div>

      {% if request.user.is_staff and account.note %}
      <div class="details">
          <h5 class="accountnotes">Account Notes</h5>
          {{ account.note|linebreaks }}
      </div>
      {% endif %}
      </div>




      {% if account.accountmember_set.active_depositor %}
        <h2 class="accountmembersection">
          Member Equity Holders ({{ account.active_member_count }})
        </h2> 

        <div class="profile profile-deposit_holder">
          {% with "deposit_holder" as section %}
          {% for am in account.accountmember_set.active_depositor %}
            {% include "membership/snippets/accountmember.html" %}
          {% endfor %}
          {% endwith %}
        </div>
      {% endif %}

      {% if account.accountmember_set.active_shopper %}
        <h2 class="accountmembersection">Proxy Shoppers</h2>
        <div class="profile profile-proxy">
          {% with "proxy" as section %}
          {% for am in account.accountmember_set.active_shopper %}
            {% include "membership/snippets/accountmember.html" %}
          {% endfor %}
          {% endwith %}
        </div>
      {% endif %}

      {% if account.accountmember_set.inactive %}
        <h2 class="accountmembersection">Departed</h2>
        <div class="profile profile-inactive">
          {% with "departed" as section %}
          {% for am in account.accountmember_set.inactive %}
            {% include "membership/snippets/accountmember.html" %}
          {% endfor %}
          {% endwith %}
        </div>
      {% endif %}

      <div id="transactions">
        <h2 class="accountmembersection">Transaction Log</h2>
        <table class="data" >
          <tr>
            <th>ID</th>
            <th>Time</th>
            <th>Member</th> 
            <th>Note</th>
            <th>Purchase Type</th>
            <th>Purchase Amount</th>
            <th>Payment Type</th>
            <th>Payment Amount</th>
            <th>Account Balance</th>
          </tr>
          {% for transaction in transactions|dictsortreversed:"id" %}
          <tr class="{% cycle 'odd' 'even' %}" >
            <td>{{ transaction.id }}</td>
            <td>{{ transaction.timestamp|date:"n/j/Y g:iA" }}</td>    
            <td>{{ transaction.member.user.get_full_name }}</td>
            <td>{{ transaction.note_plus_spaces }}</td>
            <td>{{ transaction.get_purchase_type_display }}</td>
            <td>{{ transaction.purchase_amount|messmoney }}</td>
            <td>{{ transaction.get_payment_type_display }}</td>
            <td>{{ transaction.payment_amount|messmoney:"payment" }}</td>
            <td>{{ transaction.account_balance|messmoney }}</td>
          </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>


  <div id="right-column">
    {% include 'membership/snippets/workshifts.html' %}
  </div>
{% endblock %}

mess/templates/membership/account_form.html
{% extends "membership/base.html" %}

{% block head %}
  <script type="text/javascript" src="{{ MEDIA_URL }}yui/yahoo/yahoo-min.js"></script>
  <script type="text/javascript" src="{{ MEDIA_URL }}yui/event/event-min.js"></script>
  <script type="text/javascript" src="{{ MEDIA_URL }}yui/connection/connection-min.js"></script> 
  <script type="text/javascript" src="{{ MEDIA_URL }}yui/yahoo-dom-event/yahoo-dom-event.js"></script>
  <script type="text/javascript" src="{{ MEDIA_URL }}js/membership.js"></script>
{% endblock %}

{% block content %}
  <div id="double-column">
    {% include "membership/snippets/page_menu.html" %}
    <div id="primary-content-wrapper">
      <h2>
        {% if edit %}
          Edit account: {{ account }} 
        {% else %}
          Add account
        {% endif %}
      </h2>
      <form class="standard" method="post">
        {% csrf_token %}
        <div class="section">
          <h3>Main</h3>
          <table class="form-table">
            {{ form }}
          </table>
        </div>
        {% include 'membership/snippets/formsets.html' %}
        <div class="save">
          <input type="submit" class="button" value="Save"/> 
          <input type="submit" class="button" name="cancel" value="Cancel" />
          <input type="submit" class="button" name="delete" value="Delete" onclick="return confirm('Do you really wish to delete account &quot;{{ account }}&quot; forever and ever?');" id="delete" />
        </div>
      </form>
    </div>
  </div>
  <!--
  <div id="right-column">
    Content here.
  </div>
  -->
{% endblock %}

{% block pop_up %}
{% endblock %}

mess/templates/membership/accountmemberflags.html
{% extends "base.html" %}

{% block content %}
  <div id="double-column">
    <div id="primary-content-wrapper">
    <h2>Page For Fixing "Member Equity Holder" And "Shopper" Flags</h2>

    <form method="post">
      {% csrf_token %}
      {{ amformset.management_form }}
      <table class="data">
        <tr>
          <th>Account</th>
          <th>Flags</th>
          <th>Member</th>
          <th>Join Date</th>
          <th>Departed Date</th>
        </tr>
        {% for form in amformset.forms %}
        <tr style="{% if form.diffacct %}border-bottom:1px solid black;{% endif %}{% if form.anomaly %} background:#fdd;{% endif %}">
          <td {% if form.diffacct %}style="padding-bottom:20pt;"{% endif %}>{{ form.id }}<a href="{{ form.instance.account.get_absolute_url }}">{{ form.instance.account }}</a></td>
          <td>Member&nbsp;Equity&nbsp;Holder:&nbsp;{{ form.account_contact }}&nbsp;&nbsp;&nbsp;&nbsp;Shopper:&nbsp;{{ form.shopper }}</td>
{% comment %} it seems the member.get_absolute_url function is too slow :(          <td><a href="{{ form.instance.member.get_absolute_url }}">{{ form.instance.member }}</a></td> {% endcomment %}
          <td>{{ form.instance.member }}</td>
          <td>{{ form.instance.member.date_joined }}</td>
          <td>{{ form.instance.member.date_departed }}</td>
        </tr>
        {% endfor %}
      </table>
      <input type="submit" value="Save">

      <br>{{ results }}
    </form>

    </div>
  </div>
{% endblock content %}

mess/templates/membership/accounts.html
{% extends "base.html" %}

{% block content %}
  <div id="double-column">
    {% include "membership/snippets/page_menu.html" %}
    <div id="primary-content-wrapper">
      {% if user.is_staff or is_staff_assistant %}	
      <form action="{% url account-add %}">
        <div class="add-button">
          <input type="submit" value="Add a new account!" />
        </div>
      </form>
      <h2>Account List</h2>
      <div class="sorter">
        <form>
          <div>
            <label for="id_search">Search:</label> {{ form.search }}
            <label for="id_sort_by">Sort by:</label> {{ form.sort_by }}
          </div>
          <div class="button">
            <input type="submit" value="Filter" class="button" />
          </div>
          <div>
            {{ form.active }} <label for="id_active">active</label>
            {{ form.inactive }} <label for="id_inactive">inactive</label>
          </div>
        </form>
      </div>
      {% endif %}
      {% include "snippets/pagination.html" %}
      <table class="data">
        <tr>
          <th>Name</th>
          <th>Members</th>
          <th>Balance</th>
        </tr>
        {% for account in page.object_list %}
          <tr class="{% cycle 'odd' 'even' %}">
            <td>
              <a href="{% url account account.id %}">{{ account.name }}</a>
            </td>
            <td>
              <ul class="ceasefire">
                {% for member in account.members.all %}
                {% if member.is_active %}
                <li>
                  <a href="{% url member member.user.username %}">{{ member }}</a> {{ member.user.get_profile.phones.all|first }} {{ member.user.email }}
                </li>
                {% else %}
                {% if inactive %}
                <li>
                  <a href="{% url member member.user.username %}">{{ member }}</a> {{ member.user.get_profile.phones.all|first }} {{ member.user.email }} ({{ member.verbose_status }})
                </li>
                {% endif %}
                {% endif %}
                {% endfor %}
              </ul>
            </td>
            <td>{{ account.balance|floatformat:2 }}</td>
          </tr>
        {% endfor %}
      </table>
      {% include "snippets/pagination.html" %}
    </div>
  </div>
{% endblock %}

mess/templates/membership/members.html
{% extends "base.html" %}

{% block content %}
<div id="double-column">
  {% include "membership/snippets/page_menu.html" %}
  <div id="primary-content-wrapper">
    <form action="{% url member-add %}">
      <div class="add-button">
        <input type="submit" value="Add a new member!" />
      </div>
    </form>
    <h2>Member List</h2>
    <div class="sorter">
      <form>
        <div>
          <label for="id_search">Search:</label> {{ form.search }} 
          <label for="id_sort_by">Sort by:</label> {{ form.sort_by }}
        </div>
        <div class="button">
          <input type="submit" value="Filter" class="button" />
        </div>
        <div>
          {{ form.active }} <label for="id_active">active</label> 
          {{ form.missing }} <label for="id_missing">missing</label>
          {{ form.departed }} <label for="id_departed">departed</label>
        </div>
      </form>  
    </div>
    {% include "snippets/pagination.html" %}
    <table class="data">
      <tr>
        <th>Name</th>
        <th>Accounts</th>
        <th>Date Joined</th>
        <th>Status</th>
        <th>Email</th>
        <th>Phone</th>
      </tr>    
      {% for member in page.object_list %}
      <tr class="{% cycle 'odd' 'even' %}">
        <td>
          <a href='{% url member member.user.username %}'>{{ member }}</a>
        </td>
        <td>
           <ul class="ceasefire">
             {% for account in member.accounts.all %}
                 <li><a href="{% url account account.id %}">{{ account }}</a></li>
             {% endfor %}
           </ul>
        </td>
        <td>{{ member.date_joined }}</td>
        <td>{{ member.verbose_status }}</td>        
        <td>
          <ul class="ceasefire">
            {% if member.user.email %}
            <li>{{ member.user.email }}</li>
            {% endif %}
          </ul>
        </td>
        <td>
          <ul class="ceasefire">
            {% for phone in member.phones.all %}
            <li>{{ phone.get_type_display }}: {{ phone.number }}</li>
            {% endfor %}
          </ul>
        </td>     
      </tr>
      {% endfor %}
    </table>
    {% include "snippets/pagination.html" %}
  </div>
</div>
{% endblock %}