mess/membership/urls.py
from django.conf.urls.defaults import *
from mess.membership import models
from mess.autocomplete.views import autocomplete
from django.db.models import Q
from django.contrib.auth import views as auth_views

autocomplete.register('account', models.Account.objects.all(), ('name__istartswith',), limit=10, label='name')

# create hook to branch autocomplete filter: '* = include inactive'
# (this doesn't belong here in urls.py, but where should it live?)
def member_spiffy_filter(query):
    if '*' in query:
        plain_query = query.strip('* ')
        return (Q(user__first_name__istartswith=plain_query) |
                Q(user__last_name__istartswith=plain_query) |
                Q(accounts__name__istartswith=plain_query))
    else:
        return (Q(id__in=models.Member.objects.active()) &
                   (Q(user__first_name__istartswith=query) |
                    Q(user__last_name__istartswith=query) |
                    Q(accounts__name__istartswith=query)))

autocomplete.register('member_spiffy', models.Member.objects.all(), member_spiffy_filter, limit=10, label=lambda m: m.autocomplete_label() )

def account_spiffy_filter(query):
    if '*' in query:
        plain_query = query.strip('* ')
        return Q(name__istartswith=plain_query)
    else:
        return ((Q(id__in=models.Account.objects.active()) |
                Q(name='One-Time Shopper')) &
                Q(name__istartswith=query))

autocomplete.register('account_spiffy', models.Account.objects.all(), account_spiffy_filter, limit=10, label=lambda a: a.autocomplete_label() )

urlpatterns = patterns('mess.membership.views',
    url(r'^accounts$', 'accounts', name='accounts'),
    url(r'^accounts/add$', 'account_form', name='account-add'),
    url(r'^accounts/(\d+)$', 'account', name='account'),
    url(r'^accounts/(\d+)/edit$', 'account_form', name='account-edit'),
    url(r'^accounts/(\d+)/depart$', 'depart_account', name='depart-account'),
    url(r'^accounts/(\d+)/loa$', 'loa_account', name='loa-account'),
    url(r'^accounts/(\d+)/templimit$', 'templimit', name='templimit'),
    url(r'^members$', 'members', name='members'),
    url(r'^members/add$', 'member_form', name='member-add'),
    url(r'^members/(\w+)$', 'member', name='member'),
    url(r'^members/(\w+)/edit$', 'member_form', name='member-edit'),
    url(r'^formset-form/(\w+)$', 'formset_form', name='membership-formset-form'),

    url(r'^(?P<username>\w+)/add_(?P<medium>\w+)/$', 'contact_form', name='membership-add-contact'),

    url(r'^(?P<username>\w+)/edit_(?P<medium>\w+)/(?P<id>\d+)$', 'contact_form', name='membership-edit-contact'),
    url(r'^(?P<username>\w+)/edit_address/(?P<id>\d+)$', 'contact_form', kwargs={'medium': 'address'}, name='membership-edit-address'),
    url(r'^(?P<username>\w+)/edit_email/(?P<id>\d+)$', 'contact_form', kwargs={'medium': 'email'}, name='membership-edit-email'),
    url(r'^(?P<username>\w+)/edit_phone/(?P<id>\d+)$', 'contact_form', kwargs={'medium': 'phone'}, name='membership-edit-phone'),

    url(r'^(?P<username>\w+)/remove_(?P<medium>\w+)/(?P<id>\d+)$', 'remove_contact', name='membership-remove-contact'),
    url(r'^(?P<username>\w+)/remove_address/(?P<id>\d+)$', 'remove_contact', kwargs={'medium': 'address'}, name='membership-remove-address'),
    url(r'^(?P<username>\w+)/remove_email/(?P<id>\d+)$', 'remove_contact', kwargs={'medium': 'email'}, name='membership-remove-email'),
    url(r'^(?P<username>\w+)/remove_phone/(?P<id>\d+)$', 'remove_contact', kwargs={'medium': 'phone'}, name='membership-remove-phone'),

    url(r'^autocomplete/(\w+)/$', autocomplete, name='membership-autocomplete'),
    url(r'^accountmemberflags/$', 'accountmemberflags', name='accountmemberflags'),

    url(r'^(?P<username>\w+)/adminresetpassword/$', 'admin_reset_password', name='admin_reset_password'),
    url(r'^signup/member/$', 'member_signup', name='member-signup'),
    url(r'^signup/member/(\d+)/edit/$', 'member_signup_edit', name='member-signup-edit'),
    url(r'^signup/member/review/$', 'member_signup_review', name='member-signup-review'),
    url(r'^signup/orientation/$', 'orientation_signup', name='orientation-signup'),

    #url(r'^rawlist/$', 'raw_list', name='membership-raw-list')
    #url('^junkx/(\w+)/$', junk, name='junkx'),
)

mess/urls.py
from django.conf import settings 
from django.conf.urls.defaults import *
from django.contrib import admin
from django.contrib.auth import views as auth_views

admin.autodiscover()

urlpatterns = patterns('',
    (r'', include('mess.core.urls')),
    (r'^accounting/', include('mess.accounting.urls')),        
    (r'^membership/', include('mess.membership.urls')),        
    (r'^forum/', include('mess.forum.urls')),
    (r'^reporting/', include('mess.reporting.urls')),        
    (r'^scheduling/', include('mess.scheduling.urls')),        
    (r'^events/', include('mess.events.urls')),        

    # IS4C connector
    (r'^is4c/', include('mess.is4c.urls')),        

    #url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^passwordchange/$', auth_views.password_change, name='auth_password_change'),
    url(r'^passwordchange/done/$', auth_views.password_change_done, name='auth_password_change_done'),
    url(r'^passwordreset/$', auth_views.password_reset, name='auth_password_reset'),
    url(r'^passwordreset/done/$', auth_views.password_reset_done, name='auth_password_reset_done'),
    url(r'^passwordreset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, name='auth_password_reset_confirm'),
    url(r'^passwordreset/complete/$', auth_views.password_reset_complete, name='auth_password_reset_complete'),

    ('^admin/(.*)', admin.site.root),
)

urlpatterns += patterns('django.views.generic.simple', 
    (r'^styleguide$', 'direct_to_template', {'template': 'styleguide.html'}),
)

# We're going to use the Django server in development, so we'll serve
# the static content for now.
if settings.DEBUG:
    urlpatterns += patterns('', 
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', 
            {'document_root': settings.MEDIA_ROOT}),
    )

mess/membership/models.py
import datetime
import string
from decimal import Decimal

from django.conf import settings
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db.models.aggregates import Min

# import scheduling models to figure what tasks a member has
from mess.scheduling import models as s_models

MEMBER_STATUS = (
    ('a', 'Active'),
    ('L', 'Leave of Absence'),
    ('m', 'Missing'),  # Member has disappeared without notice.
    ('x', 'Missing Delinquent'),  # Member has disappeared, owing money/time
    ('d', 'Departed'),
#   ('i', 'Inactive'),
)
WORK_STATUS = (
    ('w', 'Workshift'),  # Member is active and should have a workshift
    ('c', 'Committee'), # Anything not tracked shift by shift
    ('e', 'Exempt'),     # Exemptions granted for kids, health, etc.
    ('n', 'No-Workshift'), # Non-working member
    ('x', 'Non-Member'), # Not a member - only for our Non-Member account
)
EXEMPTION_TYPES = (
    ('k', 'Kids'),
    ('s', 'Seniors'),
    ('c', 'Caretaker'),
    ('p', 'Single Parent'),
    ('h', 'Health'),
    ('S', 'Special'),
)
ADDRESS_TYPES = (
    ('h','Home'),
    ('w','Work'),
    ('o','Other'),
)
PHONE_TYPES = (
    ('h','Home'),
    ('w','Work'),
    ('m','Mobile'),
    ('o','Other'),
)
EMAIL_TYPES = (
    ('p','Personal'),
    ('w','Work'),
    ('s','School'),
    ('o','Other'),
)

REFERRAL_SOURCES = (
    ('',''),
    ('Current Member','Current Member'),
    ('Website','Website'),
    ('Flyer','Flyer'),
    ('Advertisement','Advertisement'),
    ('Walked By','Walked By'),
    ('Other','Other'),
)

EQUITY_PAID_OPTIONS = (
    ('',''),
    ('200','$200 (Full Equity)'),
    ('25','$25 (Partial Equity)'),
    ('50','$50 (Partial Equity)'),
    ('100','$100 (Partial Equity)'),
    ('300','$300 (Additional Equity)'),
    ('500','$500 (Additional Equity)'),
    ('0','I will pay at orientation'),
)

today = datetime.date.today()

class MemberManager(models.Manager):
    'Custom manager to add extra methods'
    def active(self):
        return self.filter(date_missing__isnull=True, 
                           date_departed__isnull=True)

    def inactive(self):
        return self.filter(Q(date_missing__isnull=False)|
                           Q(date_departed__isnull=False))

    def present(self):
        return self.active().exclude(leaveofabsence__in=
                                     LeaveOfAbsence.objects.current())

class Member(models.Model):
    user = models.ForeignKey(User, unique=True)
    status = models.CharField(max_length=1, choices=MEMBER_STATUS,
                            default='a')
    work_status = models.CharField(max_length=1, choices=WORK_STATUS,
        default='w', help_text='This only matters for Active Members. \
        Workshift means they should have a workshift. \
        Committee means anything not tracked as a \
        regular shift, for example, COMMITTEE, BUSINESS/ORG, etc')
    has_key = models.BooleanField(default=False)
    #primary_account = models.ForeignKey('Account', blank=True, null=True)
    date_joined = models.DateField(default=datetime.date.today())
    date_missing = models.DateField(blank=True, null=True)
    date_departed = models.DateField(blank=True, null=True)
    card_number = models.CharField(max_length=128, blank=True, null=True)
    card_facility_code = models.CharField(max_length=128, blank=True, 
            null=True)
    card_type = models.CharField(max_length=128, blank=True, null=True)
    equity_held = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    equity_due = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    equity_increment = models.DecimalField(max_digits=8, decimal_places=2, default=25)

    referral_source = models.CharField(max_length=20, choices=REFERRAL_SOURCES, blank=True, null=True)
    referring_member = models.ForeignKey('self', blank=True, null=True)
    orientation = models.ForeignKey('events.Orientation', blank=True, null=True)

    objects = MemberManager()

    def __unicode__(self):
        return self.user.get_full_name()

    def equity_target(self):
        '''
        Returns the member's equity target. A member's equity target is $200 
        with the following exceptions:
        - $0 if they are only a proxy shopper
        - $150 if house is three or more people
        - $125 if house is five or more people
        '''
        shared_house_size = 0

        for acct in self.accounts.filter(shared_address=True):
            shared_house_size = max(shared_house_size, acct.active_member_count)

        # If this member is an account contact on any account, then they are 
        # a member of the co-op (not just a proxy shopper) and they owe equity
        only_a_proxy = len(AccountMember.objects.filter(member=self.id, account_contact=True)) == 0

        if only_a_proxy:
            return Decimal("0.00")
        elif shared_house_size >= 5:
            return Decimal("125.00")
        elif shared_house_size >= 3:
            return Decimal("150.00")

        return Decimal("200.00")

    def potential_new_equity_due(self):
        if (not self.is_active) or (self.is_on_loa):
            return Decimal("0.00")
        held_plus_due = self.equity_held + self.equity_due
        remaining_to_target = self.equity_target() - held_plus_due
        if remaining_to_target < 0:
            remaining_to_target = Decimal("0.00")
        return min(self.equity_increment, remaining_to_target)

    def skills(self):
        return s_models.Skill.objects.filter(
            trained_by__task__in=self.task_set.worked()).distinct()

    def untrained(self):
        return s_models.Skill.objects.exclude(
            trained_by__task__in=self.task_set.worked()).distinct()

    def qualified_tasks(self, possible=None):
        if possible is None:
            possible = s_models.Task.objects.unassigned_future()
        return possible.exclude(job__skills_required__in=self.untrained())
        
    @property
    def current_loa(self):
        loa_set = self.leaveofabsence_set.current()
        if loa_set.count():
            return loa_set[0]
        
    @property
    def is_active(self):
        return not (self.date_missing or self.date_departed)

    @property
    def is_on_loa(self):
        return bool(self.current_loa)

    @property
    def is_cashier_recently(self):
        shifts_recently = self.task_set.filter(time__range=(
            datetime.date.today()-datetime.timedelta(180), datetime.date.today()))
        cashier_shifts_recently = shifts_recently.filter(job__name__in=[
            'Cashier','After Hours Billing'], hours_worked__gt=0)
        return bool(cashier_shifts_recently.count())

    @property
    def is_cashier_today(self):
        shifts_today = self.task_set.filter(time__range=(
            datetime.date.today(), datetime.date.today()+datetime.timedelta(1)))
        cashier_shifts_today = shifts_today.filter(job__name__in=[
            'Cashier','After Hours Billing'])
        return bool(cashier_shifts_today.count())

    @property
    def name(self):
        return self.user.username

    @models.permalink
    def get_absolute_url(self):
        return ('member', [self.user.username])

    def next_shift(self):
        tasks = self.task_set.filter(time__gte=datetime.date.today())
        if tasks.count():
            return tasks[0]

    def regular_shift(self):
        tasks = self.task_set.filter(time__gte=datetime.date.today(),
                recur_rule__isnull=False)
        if tasks.count():
            return tasks[0]

    def remove_from_shifts(self, start, end=None):
        '''
        Removes member from workshifts that haven't happened yet.
        End date is optional.
        '''

        # handle start and end dates in the past
        if start < datetime.date.today():
            start = datetime.date.today()
        if end and end < datetime.date.today():
            return          # end date in past; don't mess with shifts.

        # switch all post-start tasks to new recur rule; 
        # set old recur_rule.until as our start date.
        tasks = self.task_set.filter(time__gte=start)
        r_rule_switch = {}
        for task in tasks:
            if task.recur_rule:
                if task.recur_rule in r_rule_switch:
                    new_rule = r_rule_switch[task.recur_rule]
                else:
                    new_rule = task.duplicate_recur_rule()
                    task.recur_rule.until = start
                    task.recur_rule.save()
                    r_rule_switch[task.recur_rule] = new_rule
                task.recur_rule = new_rule

            # task is inside LOA and should be released for one-time fill.
            # i.e. no longer point to any recur rule
            if end:
                if task.time.date() <= end:
                    task.recur_rule = None
                    task.member = task.account = None
                    
            # permanently remove from workshift (no end date)
            else:
                task.member = task.account = None

            task.save()

    def get_primary_account(self):
        try:
            primary = self.accounts.filter(
                    accountmember__shopper=False)[0]
        except IndexError:
            try:
                primary = self.accounts.all()[0]
            except IndexError:
                primary = Account()
        return primary

    def autocomplete_label(self):
        if self.is_active:
            return '%s %s (%s)' % (self.user.first_name, self.user.last_name, 
                               self.get_primary_account().name)
        else:
            return '* %s %s (%s)' % (self.user.first_name, self.user.last_name,
                                self.get_primary_account().name)

    @property
    def verbose_status(self):
        if self.date_departed:
            return 'Departed since %s' % self.date_departed

mess/templates/membership/snippets/accountmember.html
{% if am.shopper and am.account_contact %}
<div class="accountmemberalert">
  Proxy Shopper??!??
</div>
{% endif %}

{% if not am.shopper and not am.account_contact %}
<div class="accountmemberalert">
  Member Equity Holder??!??
</div>
{% endif %}

{% with am.member as member %}

{% include "membership/snippets/member.html" %}

{% endwith %}

mess/templates/membership/snippets/address.html
            <h5>{{ address.get_type_display }}
				
			</h5> 
            <p>
              {% if address.address1 %}
                {{ address.address1 }}<br />
              {% endif %}
              {% if address.address2 %}
                  {{ address.address2 }}<br />
              {% endif %}
              {{ address.city }}, {{ address.state }}
              {{ address.postal_code }}<br />
              {{ address.country }}<br />
           
              <a class="edit" href="{% url membership-edit-address member.user.username,address.id %}">edit</a>
              <a class="remove" href="{% url membership-remove-address member.user.username,address.id %}">remove</a>
			</p>

mess/templates/membership/snippets/contact_formset.html
{{ form }}

mess/templates/membership/snippets/formsets.html
        {% for formset, header in formsets %}
        <div class="section">
          <h3>{{ header }}</h3>
          {{ formset.management_form }}
          {% for form in formset.forms %}
          <table>
            {{ form }}
          </table>
          {% endfor %}
          <div id="{{ formset.prefix }}-writeroot" class="add">
            <a class="add" href="{# breaks when no member (on add) {% url membership-add-contact member.user.username,formset.prefix %} #}" onclick="addNew('{{ formset.prefix }}', '{% url membership-formset-form formset.prefix %}'); return false;" id="{{ formset.prefix }}-add">Add</a>
          </div>
        </div>
        {% endfor %}

mess/templates/membership/snippets/member.html
<h4>
  <a href="{% url member-edit member.user.username %}">edit</a>

      <a class="nofloat" href="{% url member member.user.username %}">{{ member }}</a>
</h4>

<div class="accountmemberside">
  <ul class="quick-info">
    {% if member.user.email %}
      <li><b>Email:</b> {{ member.user.email }}</li>
    {% endif %}


    {% for phone in member.phones.all %}
      <li><b>Phone:</b> {{ phone }}</li>
    {% endfor %}

    {% for address in member.addresses.all %}
      <li><b>Address:</b> <br>
        {{ address.address1 }}<br>
        {% if address.address2 %}{{ address.address2 }}<br>{% endif %}
        {{ address.city }}, {{ address.state }} {{ address.postal_code }}
        {% ifnotequal address.country "USA" %}
          <br>{{ address.country }}
        {% endifnotequal %}
      </li>
    {% endfor %}
  </ul>
</div>
<div class="accountmemberside">
  <ul class="quick-info">
    {% if member.date_departed %}
      <li><b>Departed:</b> {{ member.date_departed|date:"n/j/Y" }}</li>
    {% endif %}
    {% if member.date_missing %}
      <li><b>Missing:</b> {{ member.date_missing|date:"n/j/Y" }}</li>
    {% endif %}

    {% ifequal section "departed" %}
      {% if am.shopper %}<li><b>Was Proxy</b></li>{% endif %}
      {% if am.account_contact %}<li><b>Was Member Equity Holder</b></li>{% endif %}
    {% endifequal %}

    {% if member.current_loa %}
      <li>
        <b>On leave:</b> {{ member.current_loa.start|date:"n/j/Y" }} 
        to {{ member.current_loa.end|date:"n/j/Y" }}
      </li>
    {% endif %}

    <li><b>Equity held:</b> {{ member.equity_held }}</li>
    <li><b>Equity due:</b> {{ member.equity_due }}</li>
    <li><b>Equity increment:</b> {{ member.equity_increment }}</li>
    <li><b>Equity target:</b> {{ member.equity_target }}</li>

    {% if am.account_contact %}
      <!-- work status is only for member equity holders -->
      <li><b>Work status:</b> {{ member.get_work_status_display }}</li>
    {% endif %}

    <li><b>Key:</b> 
      {% if member.has_key %}Has Key{% else %}No Key{% endif %}
    </li>

    {% if request.user.is_staff %}
    {% if member.card_number or member.card_facility_code or member.card_type %}
    <li><b>Key #:</b>
      {{ member.card_number }} / {{ member.card_facility_code }} / {{ member.card_type }}
    </li>
    {% endif %}
    {% endif %}

    {% if member.date_joined_is_realistic or request.user.is_staff %}
    <li><b>Joined:</b> {{ member.date_joined|date:"n/j/Y" }}</li>
    {% endif %}

    {% if member.user.groups.all %}
    <li><b>Groups:</b>{{ member.user.groups.all|join:", "}}</li>
    {% endif %}
  </ul>
</div>
<hr class="endaccountmember">

mess/templates/membership/snippets/page_menu.html
{% block page_menu %}
{% load core_tags %}
  <ul id="local-nav">
    <li><a href="{% url accounts %}"{% if location.path|match:'/membership/accounts' %} class="active"{% endif %}>Accounts</a></li>
    <li><a href="{% url members %}"{% if location.path|match:'/membership/members' %} class="active"{% endif %}>Members</a></li>
    <li class="last-item"><a {% if location.path|match:'/membership/signup/member/review' %} class="active"{% endif %} href="{% url member-signup-review %}">Member Signup Review</a></li>
  </ul>
{% endblock %}

mess/templates/membership/snippets/workshifts.html
    <h2>Workshifts (<span id="workhist_week0hider"><u>past</u></span>/<span id="workhist_future0hider"><u>future</u></span>)</h2>
      <ul class="quick-info">
        <li><b>Next Workshift:</b> {% if account.next_shift %}{{ account.next_shift.member.user.first_name }} {{ account.next_shift.time|date:"D n/j g:ia" }}<br><a href="{{ account.next_shift.get_switch_url }}">need to switch?</a>{% else %}None{% endif %}</li>
      </ul>
      <table class="acctwork">
        {% for member in account.members.all %}
          {% if member.is_active %}
            <tr><td class="task-{{ member.get_work_status_display }}">{{ member }}: {{ member.get_work_status_display }}</td></tr>
            {% if member.current_loa %}
              <tr><td class="LOA">{{ member }}: LOA {{ member.current_loa.start }} until {{ member.current_loa.end }}</td></tr>
            {% endif %}
          {% endif %}
        {% endfor %}
      </table>

      <div class="workhist"> 
        <table class="workhist" id="workhist_week0">
          {% for week in account.workhist %}
            {% if week.flagcurrent %}
              </table><table class="workhist" id="workhist_current">
            {% endif %}
            {% if week.flagfuture %}
              </table><table class="workhist" id="workhist_future0">
            {% endif %}
            <tr id="workhist_week{{ forloop.counter }}hider">
              <td>{{ week.newmonth|date:"M" }}{{ week.newyear }}</td>
              <td>&nbsp;</td>
              {% for day in week.days %}
                {% if day.workflag %}
                  <td class="task-{{ day.workflag }}{% if day.istoday %} workhist-today{% endif %}" title="{{ day.task.member }}. {{ day.task.job }}. {{ day.task.time|time:"g:ia" }}, {{ day.task.hours }} hours.  {{ day.workflag|capfirst }}"><b><u>{{ day.date|date:"j" }}</u></b></td>
                {% else %}
                  <td {% if day.istoday %}class="workhist-today"{% endif %}>{{ day.date|date:"j" }}</td>
                {% endif %}
              {% endfor %}
            </tr>
            <tr class="task-hiding-spot">
              <td colspan="9">
                <div id="workhist_week{{ forloop.counter }}">
                {% for task in week.tasks %}
                  <div class="task-{{ task.simple_workflag }}">
                    {{ task.member }} &mdash; {{ task.job }} <br>
                    {% if request.user.is_staff %}<a href="{% url scheduling-task task.id %}">{{ task.time|date:"D n/j/y" }}</a>{% else %}{{ task.time|date:"D n/j/y" }}{% endif %}, 
                    {{ task.time|time:"g:ia" }}, {{ task.hours }} hours <br>
                    {% if task.hours_worked %}<b>Worked {{ task.hours_worked }} hours</b>{% endif %}
                    <b>{{ task.workflag }}</b>
                  </div>
                {% endfor %}
                </div>
              </td>
            </tr>
          {% endfor %}
        </table>

        <script> 
            attach_hiders('workhist_future',1);
            attach_hiders('workhist_week',{{ account.workhist|length }}); 
        </script>
      click any highlighted day to show shift info
      </div>

        {% if account.members_leaveofabsence_set %}
          <h2>Leave of Absence History</h2>
          <table class="acctwork">
          {% for member in account.members.all %}
            {% for leave in member.leaveofabsence_set.all %}
              <tr><td>
                {{ member }}: LOA {{ leave.start }} until {{ leave.end }}
              </td></tr>
            {% endfor %}
          {% endfor %}
          </table>
        {% endif %}