mess/scheduling/urls.py
from django.conf.urls.defaults import *
from mess.scheduling.models import *

# phantom urls wreak havoc with {% url %} and reverse()
urlpatterns = patterns('mess.scheduling.views',
    url(r'^jobs/$', 'jobs', name="scheduling-jobs"),
    url(r'^jobs/(?P<job_id>\d+)/$', 'job', name="job"),
    url(r'^jobs/(?P<job_id>\d+)/edit$', 'job_edit', name="job-edit"),
    url(r'^jobs/add$', 'job_edit', name="job-add"),
    url(r'^schedule/$', 'schedule', name="scheduling-schedule-today"),
    url(r'^schedule/(?P<date>\d{4}-\d+-\d+)$', 'schedule', name="scheduling-schedule"),
    url(r'^task/(?P<task_id>\d+)', 'task', name="scheduling-task"),
    url(r'^timecard/$', 'timecard', name="scheduling-timecard-today"),
    url(r'^timecard/(?P<date>\d{4}-\d+-\d+)$', 'timecard', name="scheduling-timecard"),
    url(r'^reminder/(?P<date>\d{4}-\d+-\d+)$', 'reminder', name="scheduling-reminder"),
    url(r'^reminder/$', 'reminder', name="scheduling-reminder-today"),
    url(r'^rotation/$', 'rotation', name="scheduling-rotation"),
    url(r'^myschedule/$', 'myschedule', name='myschedule'),
    url(r'^trade/$', 'trade', name="trade"),
    url(r'^switch/$', 'switch', name="switch"),
    url(r'^skills/$', 'skills', name="skills"),
    url(r'^skills/(?P<skill_id>\d+)/edit$', 'skill_edit', name="skill-edit")
    #url(r'^worker-form$', 'worker_form', name='scheduling-worker-form'),
   
    #url(r'^task_list/(?P<date>\d{4}-\d+-\d+)$', 'task_list', name="task-list"),
    #url(r'^task_list/$', 'task_list', name="task-list-today"),
    #
    #url(r'^open_task_list_month/(?P<date>\d{4}-\d+)$', 'open_task_list_month', name="open-task-list-month"),
    #url(r'^open_task_list_month/$', 'open_task_list_month', name="open-task-list-current-month"),
    #url(r'^open_task_list/(?P<date>\d{4}-\d+-\d+)$', 'open_task_list', name="open-task-list"),
    #url(r'^open_task_list/$', 'open_task_list', name="open-task-list-today"),
    
    # url(r'^task_form/(?P<task_id>\d+)', 'task_form'),
    # url(r'^task_form/', 'task_form'),
    
#    url(r'^daily.html', 'daliy'),
#    url(r'^weekly.html', 'weekly'),
#    url(r'^job_list.html', 'job_list'),
    #url(r'^assign/', 'assign', name="scheduling-assign"),
    #url(r'^task/new/', 'add_task', name="add-task"),
    #url(r'^task/update/(?P<object_id>\d+)', 'update_task', name="update-task"),
    #url(r'^task/delete/(?P<object_id>\d+)', 'delete_task', name="del-task"),
   
    #url(r'^task/(?P<task_id>\d+)/assign-to/(?P<member_id>\d+)', 'assign_task', name="assign-task")
)

mess/urls.py
from django.conf import settings 
from django.conf.urls.defaults import *
from django.contrib import admin
from django.contrib.auth import views as auth_views

admin.autodiscover()

urlpatterns = patterns('',
    (r'', include('mess.core.urls')),
    (r'^accounting/', include('mess.accounting.urls')),        
    (r'^membership/', include('mess.membership.urls')),        
    (r'^forum/', include('mess.forum.urls')),
    (r'^reporting/', include('mess.reporting.urls')),        
    (r'^scheduling/', include('mess.scheduling.urls')),        
    (r'^events/', include('mess.events.urls')),        

    # IS4C connector
    (r'^is4c/', include('mess.is4c.urls')),        

    #url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^passwordchange/$', auth_views.password_change, name='auth_password_change'),
    url(r'^passwordchange/done/$', auth_views.password_change_done, name='auth_password_change_done'),
    url(r'^passwordreset/$', auth_views.password_reset, name='auth_password_reset'),
    url(r'^passwordreset/done/$', auth_views.password_reset_done, name='auth_password_reset_done'),
    url(r'^passwordreset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, name='auth_password_reset_confirm'),
    url(r'^passwordreset/complete/$', auth_views.password_reset_complete, name='auth_password_reset_complete'),

    ('^admin/(.*)', admin.site.root),
)

urlpatterns += patterns('django.views.generic.simple', 
    (r'^styleguide$', 'direct_to_template', {'template': 'styleguide.html'}),
)

# We're going to use the Django server in development, so we'll serve
# the static content for now.
if settings.DEBUG:
    urlpatterns += patterns('', 
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', 
            {'document_root': settings.MEDIA_ROOT}),
    )

mess/scheduling/models.py
import datetime
from dateutil import rrule

from django.db import models
from django.template import loader, Context
from django.utils.safestring import mark_safe

today = datetime.date.today()
todaytime = datetime.datetime(today.year, today.month, today.day)

JOB_TYPES = (
    ('s','Staff'),
    ('p','Paid'),
    ('m','Member'),
)
FREQUENCIES = (
    ('d', 'Daily'),
    ('w', 'Weekly'),
    ('m', 'Monthly'),
)

REMINDER_CALL = (
    ('n', ''),
    ('c', 'Contacted'),
    ('l', 'Left Message'),
    ('p', 'Problem w #'),
)

class Skill(models.Model):
    """
    Skills needed to perform jobs
    """
    name = models.CharField(max_length=100, unique=True)
    
#   not a good idea here due to circular import problem
#   def members(self):
#       ''' members that have the skill '''
#       return m_models.Member.objects.present().filter(
#               task__in=self.trainedbytasks()).distinct()

    def trainedbytasks(self):
        ''' tasks this skill was trained by.  used in members fn. '''
        return Task.objects.worked().filter(
                job__in=self.trained_by.all())

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Job(models.Model):
    """
    Job description / title
    """
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    type = models.CharField(max_length=1, choices=JOB_TYPES, default='m')
    deadline = models.BooleanField()
    freeze_days = models.IntegerField(default=7)
    hours_multiplier = models.IntegerField(default=1)
    skills_required = models.ManyToManyField(Skill, blank=True, 
            related_name='required_by')
    skills_trained = models.ManyToManyField(Skill, blank=True, 
            related_name='trained_by')

    def __unicode__(self):
        return self.name

    def is_dancer(self):
        return self.name[:4].lower() == 'danc'
    
    class Meta:
        ordering = ['name']


class RecurRule(models.Model):
    # use task.time for start
    #start = models.DateTimeField()
    frequency = models.CharField(max_length=1, choices=FREQUENCIES, blank=True)
    interval = models.PositiveIntegerField(blank=True)
    until = models.DateTimeField(null=True, blank=True)


class Exclusion(models.Model):
    date = models.DateTimeField()
    recur_rule = models.ForeignKey(RecurRule)


class TaskManager(models.Manager):
    'Custom manager to add extra methods'
    def unassigned(self):
        return self.filter(models.Q(member=None) | models.Q(account=None))

    def unassigned_future(self):
        return self.unassigned().filter(time__gte=today)

    def dancer(self):
        return self.filter(job__name__istartswith='danc')

    def not_dancer(self):
        return self.exclude(job__name__istartswith='danc')

    def worked(self):
        return self.filter(hours_worked__gt=0)
   
class Task(models.Model):
    """
    A task is a scheduled occurrence of a job.  The time is a start time 
    unless deadline is checked for the related job.
    """
    job = models.ForeignKey(Job)
    time = models.DateTimeField()
    hours = models.DecimalField(max_digits=4, decimal_places=2)
    note = models.TextField(blank=True)

    member = models.ForeignKey('membership.Member', null=True, blank=True)
    account = models.ForeignKey('membership.Account', null=True, blank=True)

    # hours_worked:  None = not entered   0 = did not work
    hours_worked = models.DecimalField(max_digits=4, decimal_places=2, 
            null=True, blank=True)
    excused = models.BooleanField()
    makeup = models.BooleanField()
    banked = models.BooleanField()

    recur_rule = models.ForeignKey(RecurRule, null=True, blank=True)

    reminder_call = models.CharField(max_length=1, choices=REMINDER_CALL, null=True, default='n')

    objects = TaskManager()
    
    class Meta:
        ordering = ['time', 'hours', 'job']

    def __unicode__(self):
        try:
            return u'%s, %s %sh, %s (%s)' % (self.job, 
                self.time.strftime('%Y-%m-%d %I:%M%P'), self.hours,
                self.member.user.first_name, self.account)
        except AttributeError:
            return u'%s, %s %sh' % (self.job, 
                self.time.strftime('%Y-%m-%d %I:%M%P'), self.hours)

    def get_absolute_url(self):
        return '/scheduling/task/%s' % self.id

    def get_switch_url(self):
        return '/scheduling/switch/?original=%s' % self.id

    def after_printing_horizon(self):
        return bool(self.time > todaytime + datetime.timedelta(1))

    def html_display(self):
        template = loader.get_template('scheduling/snippets/task.html')
        if self.time < todaytime:
            datehorizon = 'other'
        elif self.time < todaytime + datetime.timedelta(180):
            datehorizon = 'shortterm'
        else:
            datehorizon = 'other'
        task = self
        return template.render(Context(locals()))

    @property
    def assigned(self):
        return bool(self.member and self.account)

    @property
    def unexcused(self):
        return (self.hours_worked == 0 and not self.excused)

    @property
    def workflag(self):
        flag = ''
        if self.excused:
            flag += 'excused '
        elif self.unexcused:
            flag += 'unexcused '
        if self.makeup:
            flag += 'makeup '
        if self.banked:
            flag += 'banked '
        return flag.strip()
        # possible values: '', 'excused', 'excusedmakeup', 'excusedbanked', 'excusedmakeupbanked', 'unexcused', 'unexcusedmakeup', 'unexcusedbanked', 'unexcusedmakeupbanked', 'makeup', 'banked', 'makeupbanked'

    @property
    def simple_workflag(self):
        if 'unexcused' in self.workflag:
            return 'unexcused'
        elif ' ' in self.workflag:
            return 'complex-workflag'
        elif self.workflag != '':
            return self.workflag
        elif self.hours_worked:
            return 'worked'
        else:
            return 'scheduled'

    @property
    # this returns things like Y2 or EM3 or UB2
    def abbr_workflag(self):
        if self.hours_worked:   # gt 0
            yeu = 'Y'
            hrs = self.hours_worked
        else:
            hrs = self.hours
            if self.excused:
                yeu = 'E'
            elif self.hours_worked == 0:
                yeu = 'U'
            else:
                yeu = '_'
        mb = ''
        if self.makeup:
            mb += 'M'
        if self.banked:
            mb += 'B'
        if int(hrs) == hrs:
            hrs = str(int(hrs))
        else:
            hrs = str(float(hrs))
        return yeu + mb + hrs

    @property
    def timecard_submitted(self):
        return (self.hours_worked is not None)

    def get_end(self):
        delta_hours = datetime.timedelta(hours=float(self.hours))
        end = self.time + delta_hours
        return end

    def new_date(self):
        '''
        If they have 4 or more past shifts that they actually did this year,
        then they're no longer new.  Except if it's a cashier, then the past
        shifts have to be cashiering shifts.
        '''
        if self.member:
            trainingjobs = ['Orientation Attendee','Shadow Cashier',
                            'Cashier Training Attendee']
            oldshifts = self.member.task_set.filter(time__lte=self.time,
                time__gt=datetime.date.today() - datetime.timedelta(365),
                hours_worked__gt=0).exclude(job__name__in=trainingjobs)
            if self.job.name == 'Cashier':
                oldshifts = oldshifts.filter(job__name=self.job.name)
                # FIXME only enough time for 2 past cashier shifts...
                # remove this line in October 2009:
                if len(oldshifts) >= 2: return
            if len(oldshifts) == 0:
                return self.time
            if len(oldshifts) < 4:
                return oldshifts[0].time

    def time_minus_six_days(self):
        return self.time - datetime.timedelta(6)

    def get_next_shift(self):
        if self.recur_rule:
            future_tasks = self.recur_rule.task_set.filter(time__gt=self.time)
            if future_tasks:
                next_task = future_tasks.order_by('time')[0]
                return next_task.time

    def set_recur_rule(self, frequency, interval, until):
        exclusions = []
        if self.recur_rule:
            recur_tasks = self.recur_rule.task_set.all()
            # delete all future tasks
            future_tasks = recur_tasks.filter(time__gt=self.time)
            for task in future_tasks:
                task.delete()
            # set current recur_rule to end on previous task if there is one
            past_tasks = recur_tasks.filter(time__lt=self.time).order_by(
                    '-time')
            if past_tasks:
                previous_task = past_tasks[0]
                self.recur_rule.until = previous_task.time
                self.recur_rule.save()
            exclusions = self.recur_rule.exclusion_set.all()
        recur_rule = RecurRule(frequency=frequency, interval=interval, 
                until=until)
        recur_rule.save()
        for exclusion in exclusions:
            exclusion.recur_rule = recur_rule
        self.recur_rule = recur_rule
        self.save()

    def duplicate_recur_rule(self):
        new_rule = RecurRule(frequency=self.recur_rule.frequency, 
                             interval=self.recur_rule.interval,
                             until=self.recur_rule.until)
        new_rule.save()
        return new_rule

    def exclude_from_recur_rule(self):
        exclude_date = Exclusion(date=self.time, recur_rule=self.recur_rule)
        exclude_date.save()
        self.recur_rule = None
        self.save()

    def update_buffer(self):
        """Update the 2-year date buffer."""
        if not self.recur_rule:
            return
        frequency = getattr(rrule, 

mess/templates/scheduling/assign.html
{% extends "base.html" %}

{% block head %}
<!--CSS file (default YUI Sam Skin) -->
<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}yui/calendar/assets/skins/sam/calendar.css" media="screen" >
<!-- Custom CSS -->
<link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}css/div_list.css" media="screen"/>
<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/yui_custom.css" media="screen" >
<!-- Dependencies -->
<script type="text/javascript" src="{{ MEDIA_URL }}yui/yahoo-dom-event/yahoo-dom-event.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}yui/calendar/calendar-min.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}yui/connection/connection-min.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}yui/datasource/datasource-min.js"></script> 
<script type="text/javascript" src="{{ MEDIA_URL }}yui/autocomplete/autocomplete-min.js"></script>
<!-- Custom JS -->
<script type="text/javascript" src="{{ MEDIA_URL }}js/scheduling.js"></script>
{# <script type="text/javascript" src="{{ MEDIA_URL }}js/cal_selector.js"></script> #}

<script type="text/javascript" src="{{ MEDIA_URL }}js/base.js"></script>
<script type="text/javascript">
function init() {
    makeActive();
}
window.onload = init;
</script>
<!-- Calendar styles -->
<style type="text/css">
    {% for task in tasks %}
        .yui-skin-sam {{ task.deadline|date:".\yY .\mn .\dj" }} {text-decoration: underline;}
    {% endfor %}
</style> 

{% endblock head %}

{% block page_menu %}
<a class='button' href="schedule.html">Schedule</a>
<a class='button' href="job_list.html">Job List</a>
{% endblock %}

{% block content %}
<div id="left-column">
    {% include "scheduling/snippets/page_menu.html" %}
    <div id="primary-content-wrapper">
    <h2> <a href=""><<</a> Monday, August 3, 2008 <a href="">>></a></h2>
	  
      <table class="data" id="daily-view">
        <tr>
          <th>Time</th>
          <th>Job</th>
          <th>Workers</th>
        </tr>
        <tr class="odd">
          <td class="time">8:00 a.m. &ndash; 9:00 a.m.</td>
<td>Cashier</td>
          <td>
            <ul>
              <li><a href="">John Smith</a></li>
			  <li><a href="">John Smith</a></li>
            </ul>
          </td>
        </tr>
        <tr class="even">
          <td class="time">8:00 a.m. &ndash; 9:00 a.m.</td>
          <td>Storekeeper</td>
          <td>
            <ul>
              <li><a href="">Dude's Name</a></li>
            </ul>
          </td>
		</tr>
		<tr class="odd">
          <td class="time">8:00 a.m. &ndash; 9:00 a.m.</td>
          <td>Storekeeper</td>
          <td>
            <ul>
              <li><a href="">Dude's Name</a></li>
			  <li><a href="">Dude's Name</a></li>
            </ul>
          </td>
		</tr>
		<tr class="even">
          <td class="time">9:00 a.m. &ndash; 10:00 a.m.</td>
<td>Cashier</td>
          <td class="time">
            <ul>
              <li><a href="">Dude Name</a></li>
            </ul>
          </td>
		</tr>
		<tr class="odd">
          <td class="time">10:00 a.m. &ndash; 11:00 a.m.</td>
<td>Cashier</td>
          <td>
            <ul>
              <li><a href="">Dude's Name</a></li>
            </ul>
          </td>
		</tr>
		<tr class="even unscheduled">
          <td class="time">10:00 a.m. &ndash; 11:00 a.m.</td>
<td>Cashier</td>
          <td>
            <ul>
              <li><a class="add" href="">Unassigned</a></li>
   	          <li><a href="">Dude's Name</a></li>
            </ul>
          </td>
		</tr>
		<tr class="odd">
          <td class="time">10:00 a.m. &ndash; 11:00 a.m.</td>
<td>Cashier</td>
          <td>
            <ul>
              <li><a href="">Dude's Name</a></li>
            </ul>
          </td>
		</tr>
		<tr class="even unscheduled">
          <td class="time">10:00 a.m. &ndash; 11:00 a.m.</td>
          <td>Storekeeper</td>
          <td>
            <ul>
              <li><a class="add" href="">Unassigned</a></li>
			  <li><a href="">Dude's Name</a></li>
            </ul>
          </td>
		</tr>
		<tr class="odd">
          <td class="time">10:00 a.m. &ndash; 11:00 a.m.</td>
          <td>Storekeeper</td>
          <td>
            <ul>
              <li><a href="">Dude's Name</a></li>
            </ul>
          </td>
		</tr>
		<tr class="even">
          <td class="time">10:00 a.m. &ndash; 11:00 a.m.</td>
<td>Cashier</td>
          <td>
            <ul>
			  <li><a href="">Dude's Name</a></li>
            </ul>
          </td>
		</tr>
		<tr class="odd">
          <td class="time">10:00 a.m. &ndash; 11:00 a.m.</td>
<td>Cashier</td>
          <td>
            <ul>
              <li><a href="">Dude's Name</a></li>
			  <li><a href="">Dude's Name</a></li>
            </ul>
          </td>
		</tr>
      </table>
    </div>
</div>
<div id="right-column">
    <h3 id="right-column-heading">Calendar</h3>
	<div id="cal1Container"></div>
    {# <div id="task-list"></div> #}
    {# <div id="task-form"> #}
    </div> 
</div>

{% endblock content %}

mess/templates/scheduling/job_form.html
{% extends "base.html" %}

{% block content %}
  <div id="double-column">
  {% include "scheduling/snippets/page_menu.html" %}
    <div id="primary-content-wrapper">
      <h2>
        {% if add %}
          Add new job
        {% else %}
          Edit job: {{ job.name }} 
        {% endif %}
      </h2>
      <form class="standard" method="post">
        {% csrf_token %}
        {% if is_errors %}
          <div class="error-message">
            <h3>You have problems.</h3>
            <p>Please see specific errors in the form below.</p>
          </div>
        {% endif %}
        <table class="data ceasefire">
            {{ job_form }}
        </table>
        <input type="submit" class="button" value="Save" /> 
        <input type="submit" class="button" name="cancel" value="Cancel" />
      </form>
    </div>
  </div>
{% endblock %}

mess/templates/scheduling/jobs.html
{% extends "base.html" %}

{% block content %}
<div id="double-column">
  {% include "scheduling/snippets/page_menu.html" %}
  <div id="primary-content-wrapper">
    <form action="{% url job-add %}">
      <div class="add-button">
        <input type="submit" value="Add a new job" />
      </div>
    </form>
    <h2>Job List</h2>
    <table class="data">
      <tr>
        <th>Name</th>
        <th>Desc</th>
        <th>Type</th>
        <th>Freeze Days</th>
        <th>Hours Multiplier</th>
        <th>Skills Required</th>
        <th>Skills Trained</th>
      </tr>    
      {% for job in jobs %}
      <tr class="{% cycle 'odd' 'even' %}">
        <td>
          <a href='{% url job-edit job_id=job.id %}'>{{ job }}</a>
        </td>
        <td>{{ job.desc }} </td>
        <td>{{ job.get_type_display }}</td>        
        <td>{{ job.freeze_days }}</td>
        <td>{{ job.hours_multiplier }}</td>
        <td><ul class=ceasefire>
            {% for sk in job.skills_required.all %}
            <li><a href="{% url skill-edit sk.id %}">{{ sk }}</a></li>
            {% endfor %}</ul></td>     
        <td><ul class=ceasefire>
            {% for sk in job.skills_trained.all %}
            <li><a href="{% url skill-edit sk.id %}">{{ sk }}</a></li>
            {% endfor %}</ul></td>     
      </tr>
      {% endfor %}
    </table>
    {# {% include "snippets/pagination.html" %} #}
  </div>
</div>
{% endblock %}

mess/templates/scheduling/monthly.html
{% extends "scheduling/base.html" %}

{% block content %}
<div id="double-column">
    <ul id="local-nav">
    {% include "scheduling/snippets/page_menu.html" %}
    </ul>
    <div id="primary-content-wrapper">

        <div id="cal1Container"></div>

        <div id="task-form"></div>
        
        <div id="task-list"></div>
		
    </div>
</div>

<!--BEGIN SOURCE CODE FOR AJAX REQUEST =============================== -->
<script type="text/javascript">
    function createRequest() {
        try {
            request = new XMLHttpRequest();
        } catch (trymicrosoft) {
            try {
                request = new ActiveXObject("Msxml2.XMLHTTP");
            } catch (othermicrosoft) {
                try {
                    request = new AcitveXObject("Microsoft.XMLHTTP");
                } catch (failed) {
                    request = null;
                }
            }
        }
        
        if (request == null)
            alert("Error creating request object!");
    }
</script>
<!--END SOURCE CODE FOR AJAX REQUEST =============================== -->
<!--BEGIN SOURCE CODE FOR CALENDAR =============================== -->
<script type="text/javascript">			
    // create namespace object
	YAHOO.namespace("schedule.calendar");

    //define the initConnection
	YAHOO.schedule.calendar.initConnection = function() {
		var eLog = YAHOO.util.Dom.get("task-list");
		var eCount = 1;

		function listTasks(tasks) {
            eLog.innerHTML = tasks + eLog.innerHTML;
		}
        
        function getTasks(url) {
            createRequest();
            request.open("GET", url, true);
            request.onreadystatechange = updatePage;
            request.send(null);
        }

		function dateToLocaleString(dt, cal) {
        	var dStr = dt.getDate();
        	var mStr = dt.getMonth();
       	 	var yStr = dt.getFullYear();
        	return ("scheduling/task_list/" + yStr + "-" + mStr + "-" + dStr);
		}

		function mySelectHandler(type, args, obj) {
			var selected = args[0];
			var selDate = this.toDate(selected[0]);
			var url = dateToLocaleString(selDate, this);
			getTasks(url);
			listTasks();
		}

        function updatePage() {
            if (request.readyState == 4) {
                if (request.status == 200) {
                    var response = request.responseText.split("|");
                    document.getElementById("order").value = response[0];
                    document.getElementById("address").innerHTML = response[1].replace(/\n/g, "");
                } else
             alert("status is " + request.status);
         }
       }
       YAHOO.schedule.calendar.cal1 = new YAHOO.widget.Calendar("cal1","cal1Container");
       YAHOO.schedule.calendar.cal1.selectEvent.subscribe(mySelectHandler, YAHOO.schedule.calendar.cal1, true);
       YAHOO.schedule.calendar.cal1.render();
	}

	YAHOO.util.Event.onDOMReady(YAHOO.schedule.calendar.initConnection);
</script>
<!--END SOURCE CODE FOR CALENDAR =============================== -->

{% endblock content %}

mess/templates/scheduling/task_form.html
{% extends "base.html" %}

{% block head %}
<!--CSS file (default YUI Sam Skin) -->
{# <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}yui/calendar/assets/skins/sam/calendar.css" media="screen" > #}
<!-- Custom CSS -->
{# <link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}css/div_list.css" media="screen"/> #}
{# <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/yui_custom.css" media="screen" > #}
<!-- Dependencies -->
<script type="text/javascript" src="{{ MEDIA_URL }}yui/yahoo-dom-event/yahoo-dom-event.js"></script>
{# <script type="text/javascript" src="{{ MEDIA_URL }}yui/calendar/calendar-min.js"></script> #}
<script type="text/javascript" src="{{ MEDIA_URL }}yui/datasource/datasource-min.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}yui/connection/connection-min.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}yui/autocomplete/autocomplete-min.js"></script>
<!-- Custom JS -->
{# <script type="text/javascript" src="{{ MEDIA_URL }}js/scheduling.js"></script> #}
<script type="text/javascript" src="{{ MEDIA_URL }}js/task.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/task_events.js"></script>
{# <script type="text/javascript" src="{{ MEDIA_URL }}js/cal_selector.js"></script> #}

<!-- Calendar styles -->
<style type="text/css">
    {% for task in tasks %}
        .yui-skin-sam {{ task.deadline|date:".\yY .\mn .\dj" }} {text-decoration: underline;}
    {% endfor %}
</style> 

{% endblock head %}

{% block page_menu %}
<a class='button' href="schedule.html">Schedule</a>
<a class='button' href="job_list.html">Job List</a>
{% endblock %}

{% block content %}
<div id="left-column">
    {% include "scheduling/snippets/page_menu.html" %}
    <div id="primary-content-wrapper">
        <form class="standard" method="post" >
          {% csrf_token %}
          <table>
            <tr>
                <th>
                    <label for="id_deadline">Frequency Type:</label>
                </th>
                <td>
                    <select>
                        <option value="recurring">recurring</option>
                        <option value="one-off">one-off</option>
                        <option value="deadline">deadline</option>
                    </select>
                </td>
            </tr>
            {{ task_form }}
            <tr>
              <th></th>
              <td><input class="button" type="submit" value="Submit" /></td>
            </tr>
          </table>
        </form>
    </div>
</div>
<div id="right-column">
    <h3 id="right-column-heading">Calendar</h3>
    {# <div id="cal1Container"></div> #}
</div>

{% endblock content %}

mess/templates/scheduling/task_list.html
{# prints the list of tasks for currently selected day #}
{% if tasks %}
<ul>
{% for task in tasks %}
	<li><a href="{% url update-task task.id %}">{{task}}</a> </li>
{% endfor %}
</ul>
{% endif %}